### PR TITLE
[llvm11] DIEnumerator: change type of field

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Review by mewmew — COMMENTED** [review]
I think the change was made to allow arbitrary size integers.

For instance, in `test/Assembler/DIEnumeratorBig.ll`, there is this signed value which only fits in big int.

```llvm
!0 = !DIEnumerator(name: "D0", value: -170141183460469231731687303715884105728)
```

**Comment by dannypsnl** [comment]
Here is the origin lexer changes:

```diff
bool LLParser::ParseDIEnumerator(MDNode *&Result, bool IsDistinct) {
 #define VISIT_MD_FIELDS(OPTIONAL, REQUIRED)                                    \
   REQUIRED(name, MDStringField, );                                             \
-  REQUIRED(value, MDSignedOrUnsignedField, );                                  \
+  REQUIRED(value, MDAPSIntField, );                                            \
   OPTIONAL(isUnsigned, MDBoolField, (false));
   PARSE_MD_FIELDS();
 #undef VISIT_MD_FIELDS
 
-  if (isUnsigned.Val && value.isMDSignedField())
+  if (isUnsigned.Val && value.Val.isNegative())
     return TokError("unsigned enumerator with negative value");
 
-  int64_t Value = value.isMDSignedField()
-                      ? value.getMDSignedValue()
-                      : static_cast<int64_t>(value.getMDUnsignedValue());
+  APSInt Value(value.Val);
+  // Add a leading zero so that unsigned values with the msb set are not
+  // mistaken for negative values when used for signed enumerators.
+  if (!isUnsigned.Val && value.Val.isUnsigned() && value.Val.isSignBitSet())
+    Value = Value.zext(Value.getBitWidth() + 1);
+
   Result =
       GET_OR_DISTINCT(DIEnumerator, (Context, Value, isUnsigned.Val, name.Val));
```

**Comment by dannypsnl** [comment]
I found `APSINTVAL` in grammar using `UintLit`, thus pick it, so we might need to detail with some special case?

**Comment by mewmew** [comment]
> I found APSINTVAL in grammar using UintLit, thus pick it, so we might need to detail with some special case?

Right. The other two places where `APSINTVAL` was used was for array and vector types. For both of these cases, negative length arrays and vectors are not valid.

In the case of `DIEnumerator`, the `value` field may be either signed or unsigned. As it can also contain values of arbitrary size, we should probably be using [*big.Int](https://golang.org/pkg/math/big/#Int) for the [DIEnumerator.value](https://github.com/llir/llvm/blob/0f56456be887067d98a430de1a1092e27408dc7d/ir/metadata/specialized_metadata.go#L535) field.

As you mentioned, the context determines if it will be unsigned or signed in the case of APSINTVAL.

**Comment by dannypsnl** [comment]
Just for the record, [find-significant-set-bit-number](https://www.geeksforgeeks.org/find-significant-set-bit-number/) for later `llvm/asm` implementation.

**Comment by dannypsnl** [comment]
Anyway, I update the syntax part, logic part should be done in `llvm/asm`

**Comment by dannypsnl** [comment]
Oops, then the PR can close lol.

**Pull request closed without merging**
