### PR TITLE
llvm13: keywords

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by mewmew** [comment]
Hi @dannypsnl,

Good that you started looking at LLVM 13!

I'm quite busy for the next three weeks, after that I should be able to look at PRs and also to try and update the test cases of the `testdata` repo to LLVM 13.

If you feel like, ping me in three weeks or so :)

Wish you all the best and a happy Autumn.
Cheers,
Robin

**Comment by dannypsnl** [comment]
@mewmew around 3 weeks now!

**Comment by mewmew** [comment]
> @mewmew around 3 weeks now!

Thanks for the ping @dannypsnl!

Uni work has been a lot more time consuming than anticipated. I have an exam in three weeks and will have to focus on this work.

I really appreciate that you are eager to work on the LLVM 13 update, and would love to see this work progress.

How about we create an *llvm13* branch for the `llir/grammar` and `llir/llvm` repos? Then you push to the *llvm13* branch and don't have to wait for me with pull requests.

I would be glad to review your work before me merge into the *master* branch and by then I should have more time on my hands.

Wish you all the best and happy coding!!

Cheerful winter wishes from Sweden,
Robin

P.S. We had our first snow this weekend, felt really excited for it! How are things at yours?

**Comment by dannypsnl** [comment]
Ok

**Pull request closed without merging**
