### PR TITLE
llvm13: keywords

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by mewmew** [comment]
Good! Great to see the work on LLVM 13 getting started!

**Comment by mewmew** [comment]
@dannypsnl, do you want to update the [test cases](https://github.com/llir/testdata) to LLVM 13 (in an *llvm13* branch)? Or would you prefer if I take a look at it?

Cheers,
Robin

**Comment by dannypsnl** [comment]
Better that you would like to look at it 🙂

**Comment by mewmew** [comment]
> Better that you would like to look at it :slightly_smiling_face:

Sounds good. I'll try having a look after the holidays :)

**Pull request merged**
