### PR TITLE
[llvm11] ParseOptionalAlignment might have parens

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by mewmew** [comment]
Do you have a test case from LLVM 11.0 which uses parenthesis for alignment? Just want to take a look.

**Review by mewmew — APPROVED** [review]
LGTM.

**Comment by dannypsnl** [comment]
```diff
+bool LLParser::ParseOptionalAlignment(MaybeAlign &Alignment, bool AllowParens) {
   Alignment = None;
   if (!EatIfPresent(lltok::kw_align))
     return false;
   LocTy AlignLoc = Lex.getLoc();
   uint32_t Value = 0;
+
+  LocTy ParenLoc = Lex.getLoc();
+  bool HaveParens = false;
+  if (AllowParens) {
+    if (EatIfPresent(lltok::lparen))
+      HaveParens = true;
+  }
+
   if (ParseUInt32(Value))
     return true;
+
+  if (HaveParens && !EatIfPresent(lltok::rparen))
+    return Error(ParenLoc, "expected ')'");
+
   if (!isPowerOf2_32(Value))
     return Error(AlignLoc, "alignment is not a power of two");
   if (Value > Value::MaximumAlignment)
```

**Comment by dannypsnl** [comment]
but `llc` reports error:

```
llc: error: llc: test.ll:1:45: error: expected integer
@G = addrspace(5) constant float 1.0, align (4)
```

**Comment by dannypsnl** [comment]
quite weird, llc version:
```
LLVM (http://llvm.org/):
  LLVM version 11.1.0
  Optimized build.
  Default target: x86_64-apple-darwin20.3.0
  Host CPU: skylake
```

**Comment by dannypsnl** [comment]
圖片
seems correct

**Comment by mewmew** [comment]
> but llc reports error:

`ParseOptionalAlignment` is invoked with `AllowParens=true` only in one place in `LLParser.cpp`, namely for optional parameter attributes. For llir/grammar we can allow a superset of LLVM IR as it makes the grammar a lot easier and still supports all valid LLVM IR for these cases.

This example is valid in LLVM 11.0:
```llvm
define void @foo(i32* align(8) %a) {
	ret void
}

define i32 @main() {
	ret i32 42
}
```

**Pull request merged**
